-- Copyright 2023 Timescale, Inc.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
create schema __backfill;

-- a list of source chunks to backfill
create table __backfill.task
( priority bigint not null generated by default as identity primary key
, worked tstzrange
, copy_message text
, verified tstzrange
, verify_message text
, chunk_schema name not null
, chunk_name name not null
, hypertable_schema name not null
, hypertable_name name not null
, dimensions jsonb not null
, filter text -- e.g. `where "time" < '2023-01-06'::timestamptz`
, snapshot text
);

create unique index on __backfill.task (priority) where (worked is null);
create unique index on __backfill.task (chunk_schema, chunk_name);
create unique index on __backfill.task (priority) where (verified is null and worked is not null);

create table __backfill.session
(
  -- If we drop support for PG12 we could do
  -- id uuid default gen_random_uuid(),
  -- and add an insert statement with default values.
  id uuid not null
, created_at timestamptz default now()
, one_row_constraint bool default true not null unique check (one_row_constraint)
);
